"""
Proactive Agent — uses Ollama (local LLM) to handle LOW and MEDIUM alerts.
Runs autonomously, no human approval needed for these low-stakes actions.

Run with: python -m src.agents.proactive_agent
"""

import os
import time
from dotenv import load_dotenv
from loguru import logger

import ollama

from src.database.models import (
    get_open_alerts,
    create_intervention,
    close_alert,
)

load_dotenv()

OLLAMA_MODEL          = os.getenv("OLLAMA_MODEL", "llama3")
OLLAMA_BASE_URL       = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
POLL_INTERVAL         = int(os.getenv("PROACTIVE_AGENT_POLL_INTERVAL", "30"))
HANDLED_SEVERITIES    = {"low", "medium"}


SYSTEM_PROMPT = """You are a Customer Success AI for a SaaS company.
Your job is to write personalized, helpful outreach messages for customers
who are showing early signs of disengagement.

Rules:
- Be warm, helpful, and specific to their situation
- Never mention "churn" or that you detected a problem algorithmically
- Offer concrete value (tips, features, resources)
- Keep messages under 150 words
- Always end with a clear next step or offer

Respond ONLY with the message text — no preamble, no labels."""


def build_prompt(alert: dict) -> str:
    alert_descriptions = {
        "silent_churn": (
            f"Customer {alert['customer_name']} ({alert['plan']} plan, "
            f"${alert['mrr']}/mo) has significantly reduced their product usage "
            f"over the past week. They appear to be disengaging quietly."
        ),
        "incident": (
            f"Customer {alert['customer_name']} ({alert['plan']} plan, "
            f"${alert['mrr']}/mo) has experienced multiple errors recently. "
            f"They may be frustrated with technical issues."
        ),
        "support": (
            f"Customer {alert['customer_name']} ({alert['plan']} plan, "
            f"${alert['mrr']}/mo) has several open support tickets. "
            f"They are actively seeking help and may be struggling."
        ),
    }

    description = alert_descriptions.get(
        alert["alert_type"],
        f"Customer needs proactive outreach. Alert type: {alert['alert_type']}"
    )

    return (
        f"Write a personalized check-in email for this customer situation:\n\n"
        f"{description}\n\n"
        f"The email should re-engage them, offer relevant help, "
        f"and make them feel valued."
    )


def process_alert(alert: dict) -> None:
    """Generate and log a proactive intervention for a low/medium alert."""
    logger.info(
        f"Processing [{alert['severity'].upper()}] alert for "
        f"{alert['customer_name']} (MRR: ${alert['mrr']})"
    )

    prompt = build_prompt(alert)

    try:
        response = ollama.chat(
            model=OLLAMA_MODEL,
            messages=[
                {"role": "system",  "content": SYSTEM_PROMPT},
                {"role": "user",    "content": prompt},
            ],
        )
        message = response["message"]["content"].strip()

        # Log the intervention to the database
        create_intervention(
            alert_id     = alert["id"],
            action       = message,
            ai_reasoning = (
                f"Proactive outreach generated by Ollama ({OLLAMA_MODEL}). "
                f"Alert type: {alert['alert_type']}, severity: {alert['severity']}. "
                f"Auto-approved for low/medium severity."
            ),
            approved_by  = "auto",   # no human review needed
        )

        # Close the alert — we've taken action
        close_alert(alert["id"])

        logger.success(
            f"✅ Intervention sent for {alert['customer_name']} | "
            f"preview: {message[:80]}..."
        )

    except Exception as e:
        logger.error(f"Ollama error processing alert {alert['id']}: {e}")


def main():
    logger.info(f"Proactive Agent starting — model: {OLLAMA_MODEL}")
    logger.info(f"Polling every {POLL_INTERVAL}s for LOW/MEDIUM alerts")

    # Verify Ollama is running
    try:
        ollama.list()
        logger.success("Ollama connection verified")
    except Exception as e:
        logger.error(f"Cannot connect to Ollama at {OLLAMA_BASE_URL}: {e}")
        logger.error("Make sure Ollama is running: ollama serve")
        return

    processed_ids = set()   # avoid reprocessing in same session

    while True:
        alerts = get_open_alerts(limit=50)

        # Filter to only LOW and MEDIUM alerts not yet processed
        actionable = [
            a for a in alerts
            if a["severity"] in HANDLED_SEVERITIES
            and a["id"] not in processed_ids
        ]

        if actionable:
            logger.info(f"Found {len(actionable)} alerts to handle")
            for alert in actionable:
                process_alert(alert)
                processed_ids.add(alert["id"])
                time.sleep(2)    # brief pause between Ollama calls
        else:
            logger.debug("No new LOW/MEDIUM alerts — sleeping...")

        time.sleep(POLL_INTERVAL)


if __name__ == "__main__":
    main()
